import com.sistexperto.dto.PacienteRequest;
import com.sistexperto.dto.PacienteResponse;
import com.sistexperto.model.Paciente;

global com.sistexperto.dto.PacienteResponse pacienteResponse;
global Boolean posibleEsquizofrenia;
global Boolean noPosibleEsquizofrenia;
global Boolean posibleTemporal;

dialect "mvel"


rule "Sintomas obligatorios - Delirios"
when
    $pacienteRequest: PacienteRequest((sintomas_positivos_tipo_contenido_pensamiento=="contenido-pensamiento-ideacion-delirante-sistematizada" 
    || sintomas_positivos_tipo_contenido_pensamiento=="contenido-pensamiento-ideacion-delirante-no-sistematizada")  
    && (sintomas_positivos_alucinaciones=="No se descarta" 
    || sintomas_positivos_alucinaciones=="Si" 
    || sintomas_positivos_tipo_pensamiento=="pensamiento-disgregacion" 
    || sintomas_positivos_tipo_pensamiento=="pensamiento-incoherencia" 
    || sintomas_negativos_actividad=="actividad-abulia"
    || sintomas_negativos_actividad=="actividad-hipobulia"))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Dos (o más) de los síntomas principales, cada uno de ellos presente durante una parte significativa de tiempo durante un período de un mes. Al menos uno de ellos ha de ser delirios, alucinaciones, disgregación o incoherencia",1)   
end

rule "Sintomas obligatorios - alucinaciones "
when
    $pacienteResponse: PacienteResponse(puntaje == 0)
    $pacienteRequest: PacienteRequest((sintomas_positivos_alucinaciones=="Si" 
    || sintomas_positivos_alucinaciones=="No se descarta")
    && (sintomas_positivos_tipo_contenido_pensamiento=="contenido-pensamiento-ideacion-delirante-sistematizada" 
    || sintomas_positivos_tipo_contenido_pensamiento=="contenido-pensamiento-ideacion-delirante-no-sistematizada" 
    || sintomas_positivos_tipo_pensamiento=="pensamiento-disgregacion" 
    || sintomas_positivos_tipo_pensamiento=="pensamiento-incoherencia" 
    || sintomas_negativos_actividad=="actividad-abulia"
    || sintomas_negativos_actividad=="actividad-hipobulia"))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Dos (o más) de los síntomas principales, cada uno de ellos presente durante una parte significativa de tiempo durante un período de un mes. Al menos uno de ellos ha de ser delirios, alucinaciones, disgregación o incoherencia",1)   
    update($pacienteResponse);
end

rule "Sintomas obligatorios - Disgregacion"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_pensamiento=="pensamiento-disgregacion" 
    && (sintomas_positivos_tipo_contenido_pensamiento=="contenido-pensamiento-ideacion-delirante-sistematizada" 
    || sintomas_positivos_tipo_contenido_pensamiento=="contenido-pensamiento-ideacion-delirante-no-sistematizada" 
    || sintomas_positivos_alucinaciones=="No se descarta" 
    || sintomas_positivos_alucinaciones=="Si" 
    || sintomas_positivos_tipo_pensamiento=="pensamiento-incoherencia" 
    || sintomas_negativos_actividad=="actividad-abulia"
    || sintomas_negativos_actividad=="actividad-hipobulia"))
    $pacienteResponse: PacienteResponse(puntaje == 0)
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Dos (o más) de los síntomas principales, cada uno de ellos presente durante una parte significativa de tiempo durante un período de un mes. Al menos uno de ellos ha de ser delirios, alucinaciones, disgregación o incoherencia",1)   
end

rule "Sintomas obligatorios - Incoherencia"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_pensamiento=="pensamiento-incoherencia" 
    && (sintomas_positivos_tipo_contenido_pensamiento=="contenido-pensamiento-ideacion-delirante-sistematizada" 
    || sintomas_positivos_tipo_contenido_pensamiento=="contenido-pensamiento-ideacion-delirante-no-sistematizada" 
    || sintomas_positivos_alucinaciones=="No se descarta" 
    || sintomas_positivos_alucinaciones=="Si" 
    || sintomas_positivos_tipo_pensamiento=="pensamiento-disgregacion" 
    || sintomas_negativos_actividad=="actividad-abulia"
    || sintomas_negativos_actividad=="actividad-hipobulia")) 
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Dos (o más) de los síntomas principales, cada uno de ellos presente durante una parte significativa de tiempo durante un período de un mes. Al menos uno de ellos ha de ser delirios, alucinaciones, disgregación o incoherencia",1)   
end

rule "Sintomas obligatorios - Ninguno"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_contenido_pensamiento!="contenido-pensamiento-ideacion-delirante-sistematizada" 
    && sintomas_positivos_tipo_contenido_pensamiento!="contenido-pensamiento-ideacion-delirante-no-sistematizada" 
    && sintomas_positivos_alucinaciones=="No" 
    && sintomas_positivos_tipo_pensamiento!="pensamiento-disgregacion" 
    && sintomas_positivos_tipo_pensamiento!="pensamiento-incoherencia"
    && sintomas_negativos_actividad=="actividad-hipobulia") 
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)   
    pacienteResponse.actualizarJustificacion("No presenta alucinaciones, delirios, disgregación  o incoherencia",1)   
end




rule "Tiempo - Menor 1 mes"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_duracion == "Menos de un mes" 
    || sintomas_negativos_duracion == "Menos de un mes") 
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarJustificacion("La duración de síntomas positivos o negativos menor a un mes",1)   
end

rule "Tiempo - mayor 1 mes"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_duracion == "Mayor o igual a un mes" 
    && sintomas_negativos_duracion == "Mayor o igual a un mes") 
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 3)
    pacienteResponse.actualizarJustificacion("La duración de síntomas positivos y negativos es mayor a un mes",1)   
end




rule "Ambitos principales"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_aspecto!="aspecto-bizarro" 
    || sintomas_negativos_aspecto!="aspecto-extravagante" 
    || sintomas_negativos_aspecto!="aspecto-inadecuado" 
    || sintomas_negativos_aspecto!="aspecto-adelgazado"
    || sintomas_negativos_atencion=="atencion-hiperprosexia" 
    || sintomas_negativos_atencion=="aspecto-hipomimico" 
    || sintomas_negativos_atencion=="atencion-paraprosexia" 
    || sintomas_negativos_actividad=="actividad-abulia" 
    || sintomas_negativos_actividad=="actividad-apraxia"
    || sintomas_negativos_actividad=="actividad-ataxia" 
    || sintomas_negativos_actividad=="actividad-hipobulia" 
    || sintomas_negativos_actividad=="actividad-compulsiones" 
    || sintomas_negativos_actividad=="actividad-ecopraxia" 
    || sintomas_negativos_actividad=="actividad-manierismo" 
    || sintomas_negativos_actividad=="Esterotipia" 
    || sintomas_negativos_actividad=="actividad-negativismo" 
    || sintomas_negativos_actividad=="actividad-flexibilidad-cerea" 
    || sintomas_negativos_afectividad=="afectividad-aplanamiento-afectivo" 
    || sintomas_negativos_afectividad=="afectividad-labilidad" 
    || sintomas_negativos_afectividad=="afectividad-irritabilidad" 
    || sintomas_negativos_afectividad=="afectividad-expansivo" 
    || sintomas_negativos_afectividad=="afectividad-inapropiado" 
    || sintomas_negativos_afectividad=="afectividad-anhedonia")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Durante una parte significativa de tiempo desde el inicio del trastorno, el nivel de funcionamiento en uno o más ámbitos principales está muy por debajo del nivel alcanzado antes del inicio",1)   
end

rule "Ambitos principales - Normal"
when
    $pacienteRequest: PacienteRequest(!(sintomas_negativos_aspecto!="aspecto-bizarro" 
    || sintomas_negativos_aspecto!="aspecto-extravagante" 
    || sintomas_negativos_aspecto!="aspecto-inadecuado" 
    || sintomas_negativos_aspecto!="aspecto-adelgazado" 
    || sintomas_negativos_atencion=="atencion-hiperprosexia" 
    || sintomas_negativos_atencion=="aspecto-hipomimico" 
    || sintomas_negativos_atencion=="atencion-paraprosexia" 
    || sintomas_negativos_actividad=="actividad-abulia" 
    || sintomas_negativos_actividad=="actividad-apraxia"
    || sintomas_negativos_actividad=="actividad-ataxia" 
    || sintomas_negativos_actividad=="actividad-hipobulia" 
    || sintomas_negativos_actividad=="actividad-compulsiones" 
    || sintomas_negativos_actividad=="actividad-ecopraxia" 
    || sintomas_negativos_actividad=="actividad-manierismo" 
    || sintomas_negativos_actividad=="Esterotipia" 
    || sintomas_negativos_actividad=="actividad-negativismo" 
    || sintomas_negativos_actividad=="actividad-flexibilidad-cerea" 
    || sintomas_negativos_afectividad=="afectividad-aplanamiento-afectivo" 
    || sintomas_negativos_afectividad=="afectividad-labilidad" 
    || sintomas_negativos_afectividad=="afectividad-irritabilidad" 
    || sintomas_negativos_afectividad=="afectividad-expansivo" 
    || sintomas_negativos_afectividad=="afectividad-inapropiado" 
    || sintomas_negativos_afectividad=="afectividad-anhedonia"))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("No presenta un bajo nivel de funcionamiento en ambitos principales",1)   
end





rule "Antecedentes - presencia de delirios o alucinaciones"
when
    $pacienteRequest: PacienteRequest((transtorno_autista=="Si" 
    || transtorno_comunicacion=="Si") 
    && (sintomas_positivos_alucinaciones=="Si" 
    || sintomas_positivos_tipo_contenido_pensamiento== "contenido-pensamiento-ideacion-delirante-sistematizada" 
    || sintomas_positivos_tipo_contenido_pensamiento=="contenido-pensamiento-ideacion-delirante-no-sistematizada"))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Existen antecedentes de un trastorno del espectro autista o de un trastorno de la comunicación de inicio en la infancia y presenta delirios o alucinaciones",1)   
end

rule "Antecedentes - sin presencia de sintomas_positivos_delirios o alucinaciones"
when
    $pacienteRequest: PacienteRequest((transtorno_autista=="Si" 
    || transtorno_comunicacion=="Si") 
    && sintomas_positivos_tipo_contenido_pensamiento!= "contenido-pensamiento-ideacion-delirante-sistematizada" 
    && sintomas_positivos_tipo_contenido_pensamiento!="contenido-pensamiento-ideacion-delirante-no-sistematizada" 
    && sintomas_positivos_alucinaciones=="No")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarJustificacion("Existen antecedentes de un trastorno del espectro autista o de un trastorno de la comunicación de inicio en la infancia pero no posee delirios o alucinaciones",1)   
end

rule "Sin antecedente de autismo y transtorno_comunicacion en la infancia"
when
    $pacienteRequest: PacienteRequest(transtorno_autista=="No" 
    || transtorno_comunicacion=="No") 
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("No existen antecedentes de un trastorno del espectro autista o de un trastorno de la comunicación de inicio en la infancia",1)   
end



rule "Diagnosticos descartados"
when
    $pacienteRequest: PacienteRequest(transtorno_esquizoafectivo=="No" 
    && transtorno_bipolar=="No" 
    && transtorno_depresivo=="No")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Se han descartado el trastorno esquizoafectivo y el trastorno depresivo o bipolar con características psicóticas",1)   
end

rule "Diagnosticos no descartados"
when
    $pacienteRequest: PacienteRequest(transtorno_esquizoafectivo=="Si" 
    || transtorno_bipolar=="Si" 
    || transtorno_depresivo=="Si")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    //cambiar por un mensaje mas entendible
    pacienteResponse.actualizarJustificacion("No se han descartado el trastorno esquizoafectivo y el trastorno depresivo o bipolar con características psicóticas",1)   
end



rule "Efectos fisiologicos - No"
when
    $pacienteRequest: PacienteRequest(sustancias=="No")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("El trastorno no se puede atribuir a los efectos fisiológicos de una sustancia u otra afección médica",1)   
end

rule "Efectos fisiologicos - Si"
when
    $pacienteRequest: PacienteRequest(sustancias=="Si")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0)
    pacienteResponse.actualizarJustificacion("El trastorno se podría atribuír a los efectos fisiológicos de una sustancia u otra afección médica",1)   
    pacienteResponse.actualizarRecomendacion("Se recomienda descartar que los síntomas se deban a efectos secundarios de otras medicaciones o al consumo de sustancias",1)   
end




rule "Causa organica - No"
when
    $pacienteRequest: PacienteRequest(estudio_causa_natural=="estudio-causa-natural-no")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Los síntomas no se deben a una causa orgánica",1)   
end

rule "Causa organica - Si"
when
    $pacienteRequest: PacienteRequest(estudio_causa_natural=="estudio-causa-natural-si")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarJustificacion("Los síntomas se pueden atribuír a una causa orgánica",1)   
end

rule "Causa organica - No evalua"
when
    $pacienteRequest: PacienteRequest(estudios=="No")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("No se evalúa causa orgánica",1)   
end



rule "PUNTAJE: Alucinaciones - Si"
when
    $pacienteRequest: PacienteRequest( sintomas_positivos_alucinaciones=="Si")

then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    //pacienteResponse.revisarCenestesicas($pacienteRequest: PacienteRequest(sintomas_positivos_tipo_alucinaciones))
    pacienteResponse.actualizarJustificacion("Presenta alucinaciones",1)   
end


rule "PUNTAJE: Alucinaciones - No se descarta"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_alucinaciones=="No se descarta")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 3)
    pacienteResponse.actualizarJustificacion("No se descartan alucinaciones",1)   
end

rule "PUNTAJE: Alucinaciones - No"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_alucinaciones=="No")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarJustificacion("No posee alucinaciones",1)   
end

rule "RECOMENDACION: Alucinaciones - Cenestésicas"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_alucinaciones=="alucinaciones-cenestesicas")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarRecomendacion("Se recomienda evaluar esquizofrenia cenestésica",1)   
end

rule "RECOMENDACION: Alucinaciones - Visuales"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_alucinaciones=="alucinaciones-visuales" 
    && sustancias=="No")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarRecomendacion("Se recomienda descartar efectos secundarios de otras medicaciones y consumo de sustancias",1)   
end

rule "RECOMENDACION: Alucinaciones - Olfativas sin estudios"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_alucinaciones=="alucinaciones-olfativas" 
    && estudios=="estudios-no")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarRecomendacion("Se recomienda realizar estudios para evaluar causas orgánicas",1)   
end

rule "RECOMENDACION: Alucinaciones - Olfativas con estudios"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_alucinaciones=="alucinaciones-olfativas" 
    && estudio_causa_natural=="estudio-causa-natural-si")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarRecomendacion("Se recomienda realizar derivar a neurología",1)   
end





rule "PUNTAJE: Delirios - Si"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_contenido_pensamiento== "contenido-pensamiento-ideacion-delirante-sistematizada" 
    || sintomas_positivos_tipo_contenido_pensamiento== "contenido-pensamiento-ideacion-delirante-no-sistematizada" )
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Presenta delirios",1)   
end

rule "PUNTAJE: Delirios - No"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_contenido_pensamiento!= "contenido-pensamiento-ideacion-delirante-sistematizada" 
    && sintomas_positivos_tipo_contenido_pensamiento!= "contenido-pensamiento-ideacion-delirante-no-sistematizada")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarJustificacion("No presenta delirios",1)   
end




rule "PUNTAJE: Edad - Menor"
when
    $pacienteRequest: PacienteRequest( edad < 12 )
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 1)
    pacienteResponse.actualizarJustificacion("Es infante",1)
end

rule "PUNTAJE: Edad - Adolescente hombre"
when
    $pacienteRequest: PacienteRequest((edad >= 12 && edad <= 25 ) && sexo=="Masculino")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 3)
    // por que 3 y no 5?
    pacienteResponse.actualizarJustificacion("Está en la edad de más riesgo",1)   
end

rule "PUNTAJE: Edad - Adulto masculino menor de 60"
when
    $pacienteRequest: PacienteRequest(sexo=="Masculino" && (edad > 25 && edad <= 59))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 2)
    pacienteResponse.actualizarJustificacion("Es un adulto menor de 60",1)   
end

rule "PUNTAJE: Edad - Adolescente mujer"
when
    $pacienteRequest: PacienteRequest((edad >= 12 && edad <= 30) && sexo=="Femenino")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Está en la edad de más riesgo",1)   
end

rule "PUNTAJE: Edad - Adulto femenino menor de 60"
when
    $pacienteRequest: PacienteRequest(sexo=="Femenino" &&
     (edad >= 30 && edad <= 59))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 2)
    pacienteResponse.actualizarJustificacion("Es adulto menor de 60",1)   
end


rule "PUNTAJE: Edad - Mayor "
when
    $pacienteRequest: PacienteRequest(edad > 59 )
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarJustificacion("Es un adulto mayor",1)   
end




rule "PUNTAJE: Tipo de lenguaje - Particularidades"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_lenguaje == "lenguaje-taquilalia" 
    || sintomas_positivos_tipo_lenguaje == "lenguaje-verborragia" 
    || sintomas_positivos_tipo_lenguaje == "lenguaje-bradilalia" 
    || sintomas_positivos_tipo_lenguaje == "lenguaje-mutismo")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 1)
    pacienteResponse.actualizarJustificacion("Presenta particularidades en el lenguaje que no son características de esquizofrenia (taquilalia, verborragia, bradilalia, mutismo)",1)   
end

rule "PUNTAJE: Tipo de lenguaje - Frecuentes"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_lenguaje!= "lenguaje-sin-particularidades" 
    && sintomas_positivos_tipo_lenguaje != "lenguaje-latencia" 
    &&!(sintomas_positivos_tipo_lenguaje == "lenguaje-taquilalia" 
    || sintomas_positivos_tipo_lenguaje == "lenguaje-verborragia" 
    || sintomas_positivos_tipo_lenguaje == "lenguaje-bradilalia" 
    || sintomas_positivos_tipo_lenguaje == "lenguaje-latencia" 
    || sintomas_positivos_tipo_lenguaje == "lenguaje-mutismo"))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 3)
    pacienteResponse.actualizarJustificacion("Presenta particularidades del lenguaje características de esquizofrenia",1)   
end

rule "PUNTAJE: Tipo de lenguaje - más común"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_lenguaje == "lenguaje-latencia")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 4)
    pacienteResponse.actualizarJustificacion("Presenta particularidades del lenguaje características de esquizofrenia (latencia de respuesta)",1)   
end

rule "PUNTAJE: Tipo de lenguaje - Sin particularidades"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_lenguaje=="lenguaje-sin-particularidades")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarJustificacion("No presenta particularidades en el lenguaje",1)   
end




rule "PUNTAJE: Pensamiento - principales"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_pensamiento=="pensamiento-disgregacion" 
    || sintomas_positivos_tipo_pensamiento=="pensamiento-incoherencia")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +5 )
    pacienteResponse.actualizarJustificacion("Presenta particularidades del pensamiento características de esquizofrenia",1)   
end

rule "PUNTAJE: Pensamiento - Particularidades"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_pensamiento!="pensamiento-sin-particularidades" 
    && sintomas_positivos_tipo_pensamiento!="pensamiento-disgregacion" 
    && sintomas_positivos_tipo_pensamiento!="pensamiento-incoherencia")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +4 )  
    pacienteResponse.actualizarJustificacion("Presenta particularidades en el pensamiento",1)   
end

rule "PUNTAJE: Pensamiento - Sin particularidades"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_pensamiento=="pensamiento-sin-particularidades")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarJustificacion("No presenta particularidades en el pensamiento",1)   
end




rule "PUNTAJE: Ritmo pensamiento - particularidades"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_ritmo_pensamiento != "ritmo-pensamiento-sin-particularidades")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +1 )
    pacienteResponse.actualizarJustificacion("Presenta particularidades en el ritmo del pensamiento",1)   
end

rule "PUNTAJE: Ritmo pensamiento - sin particularidades"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_ritmo_pensamiento =="ritmo-pensamiento-sin-particularidades")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarJustificacion("No presenta particularidades en el ritmo del pensamiento",1)   
end




rule "PUNTAJE: Contenido pensamiento - particularidades más comunes"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_contenido_pensamiento!="contenido-pensamiento-sin-particularidades" 
    && !(sintomas_positivos_tipo_contenido_pensamiento== "contenido-pensamiento-idea-obsesiva" 
    || sintomas_positivos_tipo_contenido_pensamiento=="contenido-pensamiento-idea-fija")
    && !(sintomas_positivos_tipo_contenido_pensamiento== "contenido-pensamiento-ideas-muerte" 
    || sintomas_positivos_tipo_contenido_pensamiento=="contenido-pensamiento-ideas-suicidas"))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +5 )
    pacienteResponse.actualizarJustificacion("Presenta particularidades en el contenido del pensamiento más comunes en esquizofrenia (Ideación delirante sistematizada o no sistematizada)",1)   
end

rule "PUNTAJE: Contenido pensamiento - particularidades menos comunes"
when
    $pacienteRequest: PacienteRequest((sintomas_positivos_tipo_contenido_pensamiento== "contenido-pensamiento-idea-obsesiva" 
    || sintomas_positivos_tipo_contenido_pensamiento=="contenido-pensamiento-idea-fija"))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +3 )
    pacienteResponse.actualizarJustificacion("Presenta contenido del pensamiento con particularidades (idea fija u obsesiva)",1)   
end

rule "PUNTAJE: Contenido pensamiento - sin particularidades"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_contenido_pensamiento=="contenido-pensamiento-sin-particularidades")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarJustificacion("No presenta particularidades en el contenido del pensamiento",1)   
end

rule "RECOMENDACION: Contenido pensamiento - ideas de muerte o suicidas"
when
    $pacienteRequest: PacienteRequest((sintomas_positivos_tipo_contenido_pensamiento== "contenido-pensamiento-ideas-muerte" 
    || sintomas_positivos_tipo_contenido_pensamiento=="contenido-pensamiento-ideas-suicidas"))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarRecomendacion("Requiere evaluación por guardia ya que presenta idea de muerte o suicidas",1)   
end




rule "PUNTAJE: Antecedentes familiares - Si"
when
    $pacienteRequest: PacienteRequest(antecedentes_familiares=="Si")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +3 )
    pacienteResponse.actualizarJustificacion("Posee antecedentes familiares psiquiátricos",1)   
end

rule "PUNTAJE: Antecedentes familiares - No"
when
    $pacienteRequest: PacienteRequest(antecedentes_familiares=="No")
then
    
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarJustificacion("Sin antecedentes familiares psiquiátricos",1)   
end




rule "PUNTAJE: Aspecto - Normal"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_aspecto=="aspecto-facie" 
    || sintomas_negativos_aspecto=="aspecto-alinio" 
    || sintomas_negativos_aspecto=="aspecto-aseo"  )
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarJustificacion("Aspecto normal",1)   
end

rule "PUNTAJE: Aspecto - Particularidades"
when
    $pacienteRequest: PacienteRequest((sintomas_negativos_aspecto != "aspecto-facie" 
    && sintomas_negativos_aspecto != "aspecto-alinio" 
    && sintomas_negativos_aspecto != "aspecto-aseo"))
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarJustificacion("Presenta particularidades en el aspecto",1)   
end



rule "PUNTAJE: Atencion - Normal"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_atencion=="atencion-euprosexia")
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarJustificacion("Atención normal",1)   
end

rule "PUNTAJE: Atención con particularidades"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_atencion=="atencion-hipoprosexia" )
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +1 )
    pacienteResponse.actualizarJustificacion("Presenta particularidades en la atención",1)   
end

rule "PUNTAJE: Atención con particularidades más comunes"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_atencion=="atencion-hiperprosexia" 
    || sintomas_negativos_atencion=="atencion-paraprosexia")
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +5 )
    pacienteResponse.actualizarJustificacion("Presenta particularidades en la atención comunes en esquizofrenia (hiperprosexia y/o paraprosexia)",1)   
end


rule "PUNTAJE: Actividad - Normal" 
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_actividad=="actividad-normobulico" 
    || sintomas_negativos_actividad=="actividad-hiperbulia-productiva" 
    || sintomas_negativos_actividad=="actividad-apraxia" 
    || sintomas_negativos_actividad=="actividad-ataxia")
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )        
    //hiperbulia-productiva, apraxia y ataxia no son normal, esta mal mostrar ese mensaje
    //podemos dividir la regla en 2 o sino directamente sacar esos sintomas.
    pacienteResponse.actualizarJustificacion("Actividad normal",1)   
end

rule "PUNTAJE: Actividad con particularidades frecuentes"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_actividad=="actividad-hiperbulia-improductiva" 
    || sintomas_negativos_actividad=="Interceptación cinética"   )
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +4 )
    pacienteResponse.actualizarJustificacion("Atención con particularidades frecuentes",1)   
end

rule "PUNTAJE: Actividad con particularidades más comunes"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_actividad=="actividad-hipobulia" 
    || sintomas_negativos_actividad=="actividad-abulia" 
    || sintomas_negativos_actividad=="actividad-compulsiones" 
    || sintomas_negativos_actividad=="actividad-ecopraxia"
    || sintomas_negativos_actividad=="actividad-manierismo" 
    || sintomas_negativos_actividad=="actividad-estereotipia-motora" 
    || sintomas_negativos_actividad=="actividad-negativismo")
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +5 )
    pacienteResponse.actualizarJustificacion("Presenta particularidades en la actividad de las más comunes en esquizofrenia (abulia, hipobulia, compulsiones, ecopraxia, manierismo, estereotipia motora o negativismo)",1)   
end

rule "PUNTAJE: Actividad con part. - otros diagnosticos"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_actividad=="actividad-impulsiones" 
    || sintomas_negativos_actividad=="actividad-flexibilidad-cerea" )
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +1 )
    pacienteResponse.actualizarJustificacion("Particularidades de la actividad más frecuentes en otros diagnosticos",1)   
end



rule "PUNTAJE: Afectividad - más comun"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_afectividad=="afectividad-aplanamiento-afectivo")
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +5 )
    pacienteResponse.actualizarJustificacion("Particularidad de afectividad (aplanamiento afectivo) muy comun es esquizofrenia",1)   
end

rule "PUNTAJE: Afectividad - Frecuente"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_afectividad=="afectividad-hipotimia")
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +4 )
    pacienteResponse.actualizarJustificacion("Particularidad de afectividad (hipotimia) frecuente en esquizofrenia",1)   
end


rule "PUNTAJE: Afectividad - Menos frecuente"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_afectividad=="afectividad-timia-displacentera" 
    || sintomas_negativos_afectividad=="afectividad-hipertimia-displacentera")
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +2)
    pacienteResponse.actualizarJustificacion("Particularidades en afectividad menos frecuentes en esquizofrenia",1)   
end

rule "PUNTAJE: Afectividad - normal"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_afectividad=="afectividad-eutimia")
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarJustificacion("Afectividad normal",1)   
end


rule "PUNTAJE: Afectividad - Frecuentes otros diagnosticos"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_afectividad!="afectividad-aplanamiento-afectivo" 
    && sintomas_negativos_afectividad!="afectividad-hipotimia" 
    && sintomas_negativos_afectividad!="afectividad-eutimia"
    && sintomas_negativos_afectividad!="afectividad-timia-displacentera" 
    && sintomas_negativos_afectividad!="afectividad-hipertimia-displacentera")
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +1 )
    pacienteResponse.actualizarJustificacion("Particularidades de afectividad frecuentes en otros diagnosticos",1)   
end



rule "Evaluar temporal"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_duracion == "Menos de un mes"  
    || sintomas_negativos_duracion== "Menos de un mes")
then
    pacienteResponse.calcularDiagnostico(true);
end

rule "Posible esquizofrenia"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_duracion == "Mayor o igual a un mes"  
    && sintomas_negativos_duracion== "Mayor o igual a un mes")
then
    pacienteResponse.calcularDiagnostico(false);
end