import com.sistexperto.dto.PacienteRequest;
import com.sistexperto.dto.PacienteResponse;
import com.sistexperto.model.Paciente;

global com.sistexperto.dto.PacienteResponse pacienteResponse;
global Boolean posibleEsquizofrenia;
global Boolean noPosibleEsquizofrenia;
global Boolean posibleTemporal;

dialect "mvel"


rule "Sintomas obligatorios - Delirios"
when
    $pacienteRequest: PacienteRequest((sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-sistematizada") 
    || sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-no-sistematizada"))  
    && (sintomas_positivos_alucinaciones=="No se descarta" 
    || sintomas_positivos_alucinaciones=="Si" 
    || sintomas_positivos_tipo_pensamiento.contains("pensamiento-disgregacion") 
    || sintomas_positivos_tipo_pensamiento.contains("pensamiento-incoherencia" )
    || sintomas_negativos_actividad=="actividad-abulia"
    || sintomas_negativos_actividad=="actividad-hipobulia"))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Dos (o más) de los síntomas principales, cada uno de ellos presente durante una parte significativa de tiempo durante un período de un mes. Al menos uno de ellos ha de ser delirios, alucinaciones, disgregación o incoherencia",1)   
    pacienteResponse.actualizarReglasEjecutadas("Sintomas obligatorios - Delirios"); 
end

rule "Sintomas obligatorios - Alucinaciones "
when
    $pacienteRequest: PacienteRequest((sintomas_positivos_alucinaciones=="Si" 
    || sintomas_positivos_alucinaciones=="No se descarta") 
    && sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-sistematizada")==false 
    && sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-no-sistematizada")==false
    && (sintomas_positivos_tipo_pensamiento.contains("pensamiento-disgregacion") 
    || sintomas_positivos_tipo_pensamiento.contains("pensamiento-incoherencia" )
    || sintomas_negativos_actividad=="actividad-abulia"
    || sintomas_negativos_actividad=="actividad-hipobulia"))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Dos (o más) de los síntomas principales, cada uno de ellos presente durante una parte significativa de tiempo durante un período de un mes. Al menos uno de ellos ha de ser delirios, alucinaciones, disgregación o incoherencia",1)   
    pacienteResponse.actualizarReglasEjecutadas("Sintomas obligatorios - Alucinaciones"); 
end

rule "Sintomas obligatorios - Disgregacion"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_pensamiento.contains("pensamiento-disgregacion") 
    && sintomas_positivos_alucinaciones=="No" 
    && sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-sistematizada")==false 
    && sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-no-sistematizada")==false
    && (sintomas_negativos_actividad=="actividad-abulia"  //no evaluo incoherencia porque son los dos discurso desorganizado
    || sintomas_negativos_actividad=="actividad-hipobulia"))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Dos (o más) de los síntomas principales, cada uno de ellos presente durante una parte significativa de tiempo durante un período de un mes. Al menos uno de ellos ha de ser delirios, alucinaciones, disgregación o incoherencia",1)   
    pacienteResponse.actualizarReglasEjecutadas("Sintomas obligatorios - Disgregacion"); 
end

rule "Sintomas obligatorios - Incoherencia"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_pensamiento.contains("pensamiento-incoherencia") 
    && sintomas_positivos_alucinaciones=="No" 
    && sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-sistematizada")==false 
    && sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-no-sistematizada")==false
    && ( sintomas_negativos_actividad=="actividad-abulia"   //no cuento disgregacion porque tambien es discurso desorganizado
    || sintomas_negativos_actividad=="actividad-hipobulia")) 
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Dos (o más) de los síntomas principales, cada uno de ellos presente durante una parte significativa de tiempo durante un período de un mes. Al menos uno de ellos ha de ser delirios, alucinaciones, disgregación o incoherencia",1)   
    pacienteResponse.actualizarReglasEjecutadas("Sintomas obligatorios - Incoherencia"); 
end

rule "Sintomas obligatorios - Ninguno"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-sistematizada")==false 
    && sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-no-sistematizada")==false
    && sintomas_positivos_alucinaciones=="No" 
    && sintomas_positivos_tipo_pensamiento.contains("pensamiento-disgregacion")==false 
    && sintomas_positivos_tipo_pensamiento.contains("pensamiento-incoherencia")==false)  //Aca no evalua hipobulia porque no es de los obligatorios
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)   
    pacienteResponse.actualizarJustificacion("No presenta alucinaciones, delirios, disgregación o incoherencia",1)   
    pacienteResponse.actualizarReglasEjecutadas("Sintomas obligatorios - Ninguno"); 
end



rule "Tiempo - Menor 1 mes"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_duracion == "Menos de un mes" 
    || sintomas_negativos_duracion == "Menos de un mes") 
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarJustificacion("La duración de síntomas positivos o negativos menor a un mes",1)   
    pacienteResponse.actualizarReglasEjecutadas("Tiempo - Menor 1 mes"); 
end

rule "Tiempo - Mayor 1 mes"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_duracion == "Mayor o igual a un mes" 
    && sintomas_negativos_duracion == "Mayor o igual a un mes") 
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("La duración de síntomas positivos y negativos es mayor a un mes",1)   
    pacienteResponse.actualizarReglasEjecutadas("Tiempo - Mayor 1 mes"); 
end




rule "Ambitos principales"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_aspecto.contains("aspecto-bizarro") 
    || sintomas_negativos_aspecto.contains("aspecto-extravagante") 
    || sintomas_negativos_aspecto.contains("aspecto-inadecuado") 
    || sintomas_negativos_aspecto.contains("aspecto-adelgazado")
    || sintomas_negativos_atencion=="atencion-hiperprosexia" 
    || sintomas_negativos_atencion=="aspecto-hipomimico" 
    || sintomas_negativos_atencion=="atencion-paraprosexia" 
    || sintomas_negativos_actividad=="actividad-abulia" 
    || sintomas_negativos_actividad=="actividad-apraxia" 
    || sintomas_negativos_actividad=="actividad-ataxia" 
    || sintomas_negativos_actividad=="actividad-hipobulia" 
    || sintomas_negativos_actividad=="actividad-compulsiones" 
    || sintomas_negativos_actividad=="actividad-ecopraxia" 
    || sintomas_negativos_actividad=="actividad-manierismo" 
    || sintomas_negativos_actividad=="actividad-estereotipia-motora" 
    || sintomas_negativos_actividad=="actividad-negativismo" 
    || sintomas_negativos_actividad=="actividad-flexibilidad-cerea" 
    || sintomas_negativos_afectividad.contains("afectividad-aplanamiento-afectivo") 
    || sintomas_negativos_afectividad.contains("afectividad-labilidad") 
    || sintomas_negativos_afectividad.contains("afectividad-irritabilidad") 
    || sintomas_negativos_afectividad.contains("afectividad-expansivo") 
    || sintomas_negativos_afectividad.contains("afectividad-inapropiado") 
    || sintomas_negativos_afectividad.contains("afectividad-anhedonia"))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Durante una parte significativa de tiempo desde el inicio del trastorno, el nivel de funcionamiento en uno o más ámbitos principales está muy por debajo del nivel alcanzado antes del inicio",1)   
    pacienteResponse.actualizarReglasEjecutadas("Ambitos principales"); 
end

rule "Ambitos principales - Normal"
when
    $pacienteRequest: PacienteRequest((sintomas_negativos_aspecto.contains("aspecto-bizarro")==false 
    && sintomas_negativos_aspecto.contains("aspecto-extravagante")==false 
    && sintomas_negativos_aspecto.contains("aspecto-inadecuado")==false 
    && sintomas_negativos_aspecto.contains("aspecto-adelgazado")==false 
    && sintomas_negativos_atencion!="atencion-hiperprosexia" 
    && sintomas_negativos_atencion!="aspecto-hipomimico" 
    && sintomas_negativos_atencion!="atencion-paraprosexia" 
    && sintomas_negativos_actividad!="actividad-abulia" 
    && sintomas_negativos_actividad!="actividad-apraxia"
    && sintomas_negativos_actividad!="actividad-ataxia" 
    && sintomas_negativos_actividad!="actividad-hipobulia" 
    && sintomas_negativos_actividad!="actividad-compulsiones" 
    && sintomas_negativos_actividad!="actividad-ecopraxia" 
    && sintomas_negativos_actividad!="actividad-manierismo" 
    && sintomas_negativos_actividad!="actividad-estereotipia-motora" 
    && sintomas_negativos_actividad!="actividad-negativismo" 
    && sintomas_negativos_actividad!="actividad-flexibilidad-cerea" 
    && sintomas_negativos_afectividad.contains("afectividad-aplanamiento-afectivo")==false
    && sintomas_negativos_afectividad.contains("afectividad-labilidad")==false 
    && sintomas_negativos_afectividad.contains("afectividad-irritabilidad")==false 
    && sintomas_negativos_afectividad.contains("afectividad-expansivo")==false 
    && sintomas_negativos_afectividad.contains("afectividad-inapropiado")==false 
    && sintomas_negativos_afectividad.contains("afectividad-anhedonia")==false))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarJustificacion("No presenta un bajo nivel de funcionamiento en ambitos principales",1)   
    pacienteResponse.actualizarReglasEjecutadas("Ambitos principales - Normal"); 
end





rule "Antecedentes - Síntomas requeridos"
when
    $pacienteRequest: PacienteRequest((trastorno_autista=="Si" 
    || trastorno_comunicacion=="Si") 
    && (sintomas_positivos_alucinaciones=="Si" 
    || sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-sistematizada")
    || sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-no-sistematizada") 
    || sintomas_positivos_tipo_pensamiento.contains("pensamiento-disgregacion")
    || sintomas_positivos_tipo_pensamiento.contains("pensamiento-incoherencia")))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Existen antecedentes de un trastorno del espectro autista o de un trastorno de la comunicación de inicio en la infancia y presenta delirios o alucinaciones",1)   
    pacienteResponse.actualizarReglasEjecutadas("Antecedentes - Síntomas requeridos"); 
end

rule "Antecedentes - Sin síntomas requeridos"
when
    $pacienteRequest: PacienteRequest((trastorno_autista=="Si" 
    || trastorno_comunicacion=="Si") 
    && sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-sistematizada")==false
    && sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-no-sistematizada")==false
    && sintomas_positivos_alucinaciones=="No" 
    && sintomas_positivos_tipo_pensamiento.contains("pensamiento-disgregacion")==false 
    && sintomas_positivos_tipo_pensamiento.contains("pensamiento-incoherencia")==false)
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarJustificacion("Existen antecedentes de un trastorno del espectro autista o de un trastorno de la comunicación de inicio en la infancia pero no posee delirios o alucinaciones",1)   
    pacienteResponse.actualizarReglasEjecutadas("Antecedentes - Sin síntomas requeridos"); 
end

rule "Sin antecedente de autismo y trastorno de la comunicacion en la infancia"
when
    $pacienteRequest: PacienteRequest(trastorno_autista=="No" 
    && trastorno_comunicacion=="No") 
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarJustificacion("No existen antecedentes de un trastorno del espectro autista o de un trastorno de la comunicación de inicio en la infancia",1)   
    pacienteResponse.actualizarReglasEjecutadas("Sin antecedente de autismo y trastorno de la comunicacion en la infancia"); 
end



rule "Diagnosticos descartados"
when
    $pacienteRequest: PacienteRequest(trastorno_esquizoafectivo=="No" 
    && trastorno_bipolar=="No" 
    && trastorno_depresivo=="No")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Se han descartado el trastorno esquizoafectivo y el trastorno depresivo o bipolar con características psicóticas",1)   
    pacienteResponse.actualizarReglasEjecutadas("Diagnosticos descartados"); 
end

rule "Diagnostico trastorno esquizoafectivo no descartado"
when
    $pacienteRequest: PacienteRequest(trastorno_esquizoafectivo=="Si")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarJustificacion("Presenta o no se ha descartado el trastorno esquizoafectivo",1)   
    pacienteResponse.actualizarReglasEjecutadas("Diagnostico trastorno esquizoafectivo no descartado"); 
end

rule "Diagnostico trastorno bipolar no descartado"
when
    $pacienteRequest: PacienteRequest(trastorno_bipolar=="Si")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarJustificacion("Presenta o no se ha descartado el trastorno bipolar con características psicóticas",1)   
    pacienteResponse.actualizarReglasEjecutadas("Diagnostico trastorno bipolar no descartado"); 
end

rule "Diagnostico depresivo no descartado"
when
    $pacienteRequest: PacienteRequest(trastorno_depresivo=="Si")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarJustificacion("Presenta o no se ha descartado el trastorno depresivo",1)   
    pacienteResponse.actualizarReglasEjecutadas("Diagnostico depresivo no descartado"); 
end



rule "Efectos fisiologicos - No"
when
    $pacienteRequest: PacienteRequest(sustancias=="No")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("El trastorno no se puede atribuir a los efectos fisiológicos de una sustancia u otra afección médica",1)   
    pacienteResponse.actualizarReglasEjecutadas("Efectos fisiologicos - No"); 
end

rule "Efectos fisiologicos - Si"
when
    $pacienteRequest: PacienteRequest(sustancias=="Si")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0)
    pacienteResponse.actualizarJustificacion("El trastorno se podría atribuir a los efectos fisiológicos de una sustancia u otra afección médica",1)   
    pacienteResponse.actualizarRecomendacion("Se recomienda descartar que los síntomas se deban a efectos secundarios de otras medicaciones o al consumo de sustancias",1)   
    pacienteResponse.actualizarReglasEjecutadas("Efectos fisiologicos - Si"); 
end




rule "Causa organica - No"
when
    $pacienteRequest: PacienteRequest(estudio_causa_natural=="estudio-causa-natural-no")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Los síntomas no se deben a una causa orgánica",1)   
    pacienteResponse.actualizarReglasEjecutadas("Causa organica - No"); 
end

rule "Causa organica - Si"
when
    $pacienteRequest: PacienteRequest(estudio_causa_natural=="estudio-causa-natural-si")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarJustificacion("Los síntomas se pueden atribuir a una causa orgánica",1)   
    pacienteResponse.actualizarReglasEjecutadas("Causa organica - Si"); 
end

rule "Causa organica - No evalua"
when
    $pacienteRequest: PacienteRequest(estudios=="No")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarJustificacion("No se evalúa causa orgánica",1)   
    pacienteResponse.actualizarReglasEjecutadas("Causa organica - No evalua"); 
end



rule "PUNTAJE: Alucinaciones - Si"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_alucinaciones=="Si")

then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Presenta alucinaciones",1)   
    pacienteResponse.actualizarReglasEjecutadas("Alucinaciones - Si"); 
end


rule "PUNTAJE: Alucinaciones - No se descarta"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_alucinaciones=="No se descarta")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 3)
    pacienteResponse.actualizarJustificacion("No se descartan alucinaciones",1)   
    pacienteResponse.actualizarReglasEjecutadas("Alucinaciones - No se descarta"); 
end

rule "PUNTAJE: Alucinaciones - No"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_alucinaciones=="No")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarJustificacion("No presenta alucinaciones",1)   
    pacienteResponse.actualizarReglasEjecutadas("Alucinaciones - No"); 
end

rule "RECOMENDACION: Alucinaciones - Cenestésicas"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_alucinaciones.contains("alucinaciones-cenestesicas"))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarRecomendacion("Se recomienda evaluar esquizofrenia cenestésica",1)   
    pacienteResponse.actualizarReglasEjecutadas("Alucinaciones - Cenestésicas"); 
end

rule "RECOMENDACION: Alucinaciones - Visuales"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_alucinaciones.contains("alucinaciones-visuales")
    && sustancias=="No")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarRecomendacion("Se recomienda descartar efectos secundarios de otras medicaciones y consumo de sustancias",1)   
    pacienteResponse.actualizarReglasEjecutadas("Alucinaciones - Visuales"); 
end

rule "RECOMENDACION: Alucinaciones - Olfativas sin estudios"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_alucinaciones.contains("alucinaciones-olfativas") 
    && estudios=="No")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarRecomendacion("Se recomienda realizar estudios para evaluar causas orgánicas para alucinaciones olfativas",1)   
    pacienteResponse.actualizarReglasEjecutadas("Alucinaciones - Olfativas sin estudios"); 
end

rule "RECOMENDACION: Alucinaciones - Olfativas con estudios"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_alucinaciones.contains("alucinaciones-olfativas" )
    && estudio_causa_natural=="estudio-causa-natural-si")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarRecomendacion("Se recomienda derivar o relaizar consulta a neurología",1)   
    pacienteResponse.actualizarReglasEjecutadas("AfectivAlucinaciones - Olfativas con estudiosidad"); 
end





rule "PUNTAJE: Delirios - Si"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-sistematizada")
    || sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-no-sistematizada") )
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Presenta delirios",1)   
    pacienteResponse.actualizarReglasEjecutadas("Delirios - Si"); 
end

rule "PUNTAJE: Delirios - No"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-sistematizada")==false 
    && sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-no-sistematizada")==false)
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarJustificacion("No presenta delirios",1)   
    pacienteResponse.actualizarReglasEjecutadas("Delirios - No"); 
end


rule "PUNTAJE: Abulia - Si"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_actividad=="actividad-abulia")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Presenta abulia",1)   
    pacienteResponse.actualizarReglasEjecutadas("Abulia - Si"); 
end



rule "PUNTAJE: Edad - Menor"
when
    $pacienteRequest: PacienteRequest( edad < 12 )
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 1)
    pacienteResponse.actualizarJustificacion("Es infante",1)
    pacienteResponse.actualizarReglasEjecutadas("Edad - Menor"); 
end

rule "PUNTAJE: Edad - Adolescente hombre"
when
    $pacienteRequest: PacienteRequest((edad >= 12 && edad <= 25 ) && sexo=="Masculino")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Se encuentra en la edad de la media de diagnóstico de esquizofrenia para hombres",1)   
    pacienteResponse.actualizarReglasEjecutadas("Edad - Adolescente hombre"); 
end

rule "PUNTAJE: Edad - Adulto masculino menor de 60"
when
    $pacienteRequest: PacienteRequest(sexo=="Masculino" && (edad > 25 && edad <= 59))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 2)
    pacienteResponse.actualizarJustificacion("Es un adulto menor de 60",1)   
    pacienteResponse.actualizarReglasEjecutadas("Edad - Adulto masculino menor de 60"); 
end

rule "PUNTAJE: Edad - Adolescente mujer"
when
    $pacienteRequest: PacienteRequest((edad >= 12 && edad <= 30) && sexo=="Femenino")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Se encuentra en la edad de la media de diagnóstico de esquizofrenia para mujeres",1)   
    pacienteResponse.actualizarReglasEjecutadas("Edad - Adolescente mujer"); 
end

rule "PUNTAJE: Edad - Adulto femenino menor de 60"
when
    $pacienteRequest: PacienteRequest(sexo=="Femenino" &&
     (edad >= 30 && edad <= 59))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 2)
    pacienteResponse.actualizarJustificacion("Es adulto menor de 60",1)   
    pacienteResponse.actualizarReglasEjecutadas("Edad - Adulto femenino menor de 60"); 
end

rule "PUNTAJE: Edad - Mayor"
when
    $pacienteRequest: PacienteRequest(edad > 59 )
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 0)
    pacienteResponse.actualizarJustificacion("Es un adulto mayor",1)   
    pacienteResponse.actualizarReglasEjecutadas("Edad - Mayor"); 
end

rule "PUNTAJE: Edad - Edad de mayor riesgo sin sexo"
when
    $pacienteRequest: PacienteRequest((edad >= 12 && edad <= 30) && (sexo=="-1" || sexo=="No-especifica"))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 5)
    pacienteResponse.actualizarJustificacion("Se encuentra en la de edad de la media de diagnóstico de esquizofrenia",1)   
    pacienteResponse.actualizarReglasEjecutadas("Edad - Edad de mayor riesgo sin sexo"); 
end






rule "PUNTAJE: Tipo de lenguaje - Más común"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_lenguaje.contains("lenguaje-latencia") )
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 4)
    pacienteResponse.actualizarJustificacion("Presenta particularidades del lenguaje características de esquizofrenia (latencia de respuesta)",1)   
    pacienteResponse.actualizarReglasEjecutadas("Tipo de lenguaje - Más común"); 
end

rule "PUNTAJE: Tipo de lenguaje - Frecuentes"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_lenguaje.contains("lenguaje-latencia")==false 
    && (sintomas_positivos_tipo_lenguaje.contains("lenguaje-musitaciones") 
    || sintomas_positivos_tipo_lenguaje.contains("lenguaje-soliloquio") 
    || sintomas_positivos_tipo_lenguaje.contains("lenguaje-neologismo")
    || sintomas_positivos_tipo_lenguaje.contains("lenguaje-jergafasia") 
    || sintomas_positivos_tipo_lenguaje.contains("lenguaje-ecolalia") 
    || sintomas_positivos_tipo_lenguaje.contains("lenguaje-pararrespuesta")
    || sintomas_positivos_tipo_lenguaje.contains("lenguaje-estereotipia-verbal")
    || sintomas_positivos_tipo_lenguaje.contains("lenguaje-verbigeracion") 
    || sintomas_positivos_tipo_lenguaje.contains("lenguaje-homofonia")))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 3)
    pacienteResponse.actualizarJustificacion("Presenta particularidades del lenguaje frecuentes de esquizofrenia",1)   
    pacienteResponse.actualizarReglasEjecutadas("Tipo de lenguaje - Frecuentes"); 
end

rule "PUNTAJE: Tipo de lenguaje - Particularidades"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_lenguaje.contains("lenguaje-latencia")==false 
    && sintomas_positivos_tipo_lenguaje.contains("lenguaje-musitaciones")==false
    && sintomas_positivos_tipo_lenguaje.contains("lenguaje-soliloquio")==false
    && sintomas_positivos_tipo_lenguaje.contains("lenguaje-neologismo")==false
    && sintomas_positivos_tipo_lenguaje.contains("lenguaje-jergafasia")==false
    && sintomas_positivos_tipo_lenguaje.contains("lenguaje-ecolalia")==false
    && sintomas_positivos_tipo_lenguaje.contains("lenguaje-pararrespuesta")==false
    && sintomas_positivos_tipo_lenguaje.contains("lenguaje-estereotipia-verbal")==false 
    && sintomas_positivos_tipo_lenguaje.contains("lenguaje-verbigeracion")==false
    && sintomas_positivos_tipo_lenguaje.contains("lenguaje-homofonia")==false
    && (sintomas_positivos_tipo_lenguaje.contains("lenguaje-taquilalia")
    || sintomas_positivos_tipo_lenguaje.contains("lenguaje-verborragia")
    || sintomas_positivos_tipo_lenguaje.contains("lenguaje-bradilalia")
    || sintomas_positivos_tipo_lenguaje.contains("lenguaje-mutismo")))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() + 1)
    pacienteResponse.actualizarJustificacion("Presenta particularidades en el lenguaje que no son características de esquizofrenia (taquilalia, verborragia, bradilalia, mutismo)",1)   
    pacienteResponse.actualizarReglasEjecutadas("Tipo de lenguaje - Particularidades"); 
end

rule "PUNTAJE: Tipo de lenguaje - Sin particularidades"
when
    $pacienteResponse: PacienteResponse(justificacion.contains("lenguaje")==false)
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_lenguaje.contains("lenguaje-sin-particularidades"))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarJustificacion("No presenta particularidades en el lenguaje",1)   
    pacienteResponse.actualizarReglasEjecutadas("Tipo de lenguaje - Sin particularidades"); 
end




rule "PUNTAJE: Pensamiento - Principales"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_pensamiento.contains("pensamiento-disgregacion") 
    || sintomas_positivos_tipo_pensamiento.contains("pensamiento-incoherencia"))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +5 )
    pacienteResponse.actualizarJustificacion("Presenta particularidades del pensamiento características de esquizofrenia",1)   
    pacienteResponse.actualizarReglasEjecutadas("Pensamiento - Principales"); 
end

rule "PUNTAJE: Pensamiento - Particularidades"
when 
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_pensamiento.contains("pensamiento-disgregacion")==false
    && sintomas_positivos_tipo_pensamiento.contains("pensamiento-incoherencia")==false 
    && (sintomas_positivos_tipo_pensamiento.contains("pensamiento-tangencial") 
    || sintomas_positivos_tipo_pensamiento.contains("pensamiento-circunstancial") 
    || sintomas_positivos_tipo_pensamiento.contains("pensamiento-minuciosidad") 
    || sintomas_positivos_tipo_pensamiento.contains("pensamiento-viscosidad") 
    || sintomas_positivos_tipo_pensamiento.contains("pensamiento-concreto") 
    || sintomas_positivos_tipo_pensamiento.contains("pensamiento-idea-fija") 
    || sintomas_positivos_tipo_pensamiento.contains("pensamiento-interceptacion-pensamiento") 
    || sintomas_positivos_tipo_pensamiento.contains("pensamiento-circunstancial")))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +4 )  
    pacienteResponse.actualizarJustificacion("Presenta particularidades en el pensamiento comunes en esquizofrenia",1)   
    pacienteResponse.actualizarReglasEjecutadas("Pensamiento - Particularidades"); 
end

rule "PUNTAJE: Pensamiento - Sin particularidades"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_pensamiento.contains("pensamiento-sin-particularidades"))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarJustificacion("No presenta particularidades en el pensamiento",1)   
    pacienteResponse.actualizarReglasEjecutadas("Pensamiento - Sin particularidades"); 
end




rule "PUNTAJE: Ritmo pensamiento - Particularidades"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_ritmo_pensamiento=="ritmo-pensamiento-taquipsiquia" 
    || sintomas_positivos_tipo_ritmo_pensamiento=="ritmo-pensamiento-bradipsiquia")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +1 )
    pacienteResponse.actualizarJustificacion("Presenta particularidades en el ritmo del pensamiento (bradipsiquia o taquipsiquia)",1)   
    pacienteResponse.actualizarReglasEjecutadas("Ritmo pensamiento - Particularidades"); 
end

rule "PUNTAJE: Ritmo pensamiento - Sin particularidades"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_ritmo_pensamiento=="ritmo-pensamiento-sin-particularidades")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarJustificacion("No presenta particularidades en el ritmo del pensamiento",1)   
    pacienteResponse.actualizarReglasEjecutadas("Ritmo pensamiento - Sin particularidades"); 
end





rule "PUNTAJE: Contenido pensamiento - Particularidades menos comunes"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-sistematizada")==false 
    && sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideacion-delirante-no-sistematizada")==false
    && (sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-idea-obsesiva") 
    || sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-idea-fija")))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +3 )
    pacienteResponse.actualizarJustificacion("Presenta contenido del pensamiento con particularidades (idea fija u obsesiva)",1)   
    pacienteResponse.actualizarReglasEjecutadas("Contenido pensamiento - Particularidades menos comunes"); 
end

rule "PUNTAJE: Contenido pensamiento - Sin particularidades"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-sin-particularidades"))
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarJustificacion("No presenta particularidades en el contenido del pensamiento",1)   
    pacienteResponse.actualizarReglasEjecutadas("Contenido pensamiento - Sin particularidades"); 
end

rule "RECOMENDACION: Contenido pensamiento - Ideas de muerte o suicidas"
when
    $pacienteRequest: PacienteRequest((sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideas-muerte")
    || sintomas_positivos_tipo_contenido_pensamiento.contains("contenido-pensamiento-ideas-suicidas")))
then
    pacienteResponse.actualizarRecomendacion("Requiere evaluación por guardia ya que presenta ideas de muerte o suicidas",1)   
    pacienteResponse.actualizarReglasEjecutadas("Contenido pensamiento - Ideas de muerte o suicidas"); 
end




rule "PUNTAJE: Antecedentes familiares - Si"
when
    $pacienteRequest: PacienteRequest(antecedentes_familiares=="Si")
then
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +3 )
    pacienteResponse.actualizarJustificacion("Posee antecedentes familiares psiquiátricos",1)   
    pacienteResponse.actualizarReglasEjecutadas("Antecedentes familiares - Si"); 
end

rule "PUNTAJE: Antecedentes familiares - No"
when
    $pacienteRequest: PacienteRequest(antecedentes_familiares=="No")
then
    
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarJustificacion("Sin antecedentes familiares psiquiátricos",1)   
    pacienteResponse.actualizarReglasEjecutadas("Antecedentes familiares - No"); 
end




rule "PUNTAJE: Aspecto - Particularidades"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_aspecto.contains("aspecto-bizarro")
    || sintomas_negativos_aspecto.contains("aspecto-extravagante")
    || sintomas_negativos_aspecto.contains("aspecto-inadecuado") 
    || sintomas_negativos_aspecto.contains("aspecto-adelgazado"))
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +5 )
    pacienteResponse.actualizarJustificacion("Presenta particularidades en el aspecto (bizarro, extravagante, inadecuado, adelgazado)",1)   
    pacienteResponse.actualizarReglasEjecutadas("Aspecto - Particularidades"); 
end

rule "PUNTAJE: Aspecto - Particularidades menos comunes"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_aspecto.contains("aspecto-bizarro")==false
    && sintomas_negativos_aspecto.contains("aspecto-extravagante")==false
    && sintomas_negativos_aspecto.contains("aspecto-inadecuado")==false
    && sintomas_negativos_aspecto.contains("aspecto-adelgazado")==false 
    && sintomas_negativos_aspecto.contains("aspecto-hipomimico"))
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +4 )
    pacienteResponse.actualizarJustificacion("Presenta particularidades en el aspecto (hipomimia)",1)   
    pacienteResponse.actualizarReglasEjecutadas("Aspecto - Particularidades menos comunes"); 
end

rule "PUNTAJE: Aspecto - Normal"
when
    $pacienteRequest: PacienteRequest((sintomas_negativos_aspecto.contains("aspecto-bizarro")==false
    && sintomas_negativos_aspecto.contains("aspecto-extravagante")==false
    && sintomas_negativos_aspecto.contains("aspecto-inadecuado")==false
    && sintomas_negativos_aspecto.contains("aspecto-adelgazado")==false 
    && sintomas_negativos_aspecto.contains("aspecto-hipomimico")== false) 
    && sintomas_negativos_aspecto.contains("aspecto-facie")
    || sintomas_negativos_aspecto.contains("aspecto-alinio")
    || sintomas_negativos_aspecto.contains("aspecto-aseo"))
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarJustificacion("Aspecto normal",1)   
    pacienteResponse.actualizarReglasEjecutadas("Aspecto - Normal"); 
end



rule "PUNTAJE: Atencion - Normal"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_atencion=="atencion-euprosexia")
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarJustificacion("Atención normal",1)   
    pacienteResponse.actualizarReglasEjecutadas("Atencion - Normal"); 
end

rule "PUNTAJE: Atención con particularidades"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_atencion=="atencion-hipoprosexia" )
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +1 )
    pacienteResponse.actualizarJustificacion("Presenta particularidades en la atención (hipoprosexia)",1)   
    pacienteResponse.actualizarReglasEjecutadas("Atención con particularidades"); 
end

rule "PUNTAJE: Atención con particularidades más comunes"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_atencion=="atencion-hiperprosexia" 
    || sintomas_negativos_atencion=="atencion-paraprosexia")
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +5 )
    pacienteResponse.actualizarJustificacion("Presenta particularidades en la atención comunes en esquizofrenia (hiperprosexia y/o paraprosexia)",1)   
    pacienteResponse.actualizarReglasEjecutadas(" Atención con particularidades más comunes"); 
end


rule "PUNTAJE: Actividad - Normal" 
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_actividad=="actividad-normobulico")
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarJustificacion("Actividad normal",1)   
    pacienteResponse.actualizarReglasEjecutadas("Actividad - Normal"); 
end

rule "PUNTAJE: Actividad con particularidades frecuentes"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_actividad=="actividad-hiperbulia-improductiva" 
    || sintomas_negativos_actividad=="actividad-interceptacion-cinetica")
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +4 )
    pacienteResponse.actualizarJustificacion("Presenta particularidades en la actividad frecuentes en esquizofrenia (interceptación cinética, hiperbulia improductiva)",1)   
    pacienteResponse.actualizarReglasEjecutadas("Actividad con particularidades frecuentes"); 
end

rule "PUNTAJE: Actividad con particularidades más comunes"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_actividad=="actividad-hipobulia" 
    || sintomas_negativos_actividad=="actividad-abulia" 
    || sintomas_negativos_actividad=="actividad-compulsiones" 
    || sintomas_negativos_actividad=="actividad-ecopraxia"
    || sintomas_negativos_actividad=="actividad-manierismo" 
    || sintomas_negativos_actividad=="actividad-estereotipia-motora" 
    || sintomas_negativos_actividad=="actividad-negativismo")
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +5 )
    pacienteResponse.actualizarJustificacion("Presenta particularidades en la actividad de las más comunes en esquizofrenia (abulia, hipobulia, compulsiones, ecopraxia, manierismo, estereotipia motora o negativismo)",1)   
    pacienteResponse.actualizarReglasEjecutadas("Actividad con particularidades más comunes"); 
end

rule "PUNTAJE: Actividad con part. - Otros diagnosticos"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_actividad=="actividad-impulsiones" 
    || sintomas_negativos_actividad=="actividad-flexibilidad-cerea" )
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +1 )
    pacienteResponse.actualizarJustificacion("Particularidades de la actividad más frecuentes en otros diagnósticos (impulsiones, flexibilidad cérea)",1)   
    pacienteResponse.actualizarReglasEjecutadas("Actividad con part. - Otros diagnosticos"); 
end

rule "RECOMENDACION: Actividad - Manierismo y sin estudios"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_actividad=="actividad-manierismo" && estudios=="No")
then 
    pacienteResponse.actualizarRecomendacion("Se recomienda realizar estudios complementarios o derivar a neurología para encontrar la causa del Manierismo",1)   
    pacienteResponse.actualizarReglasEjecutadas("Actividad - Manierismo y sin estudios"); 
end

rule "RECOMENDACION: Actividad - Manierismo y estudios SI"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_actividad=="actividad-manierismo" && estudios=="Si")
then 
    pacienteResponse.actualizarRecomendacion("Se recomienda realizar estudios complementarios o derivar a neurología para encontrar la causa del Manierismo",1)   
    pacienteResponse.actualizarReglasEjecutadas("Actividad - Manierismo y estudios SI"); 
end



rule "PUNTAJE: Afectividad - Más comun"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_afectividad.contains("afectividad-aplanamiento-afectivo"))
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +5 )
    pacienteResponse.actualizarJustificacion("Presenta aplanamiento afectivo, una particularidad de afectividad muy común es esquizofrenia",1)   
    pacienteResponse.actualizarReglasEjecutadas("Afectividad - Más comun"); 
end

rule "PUNTAJE: Afectividad - Frecuente"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_afectividad.contains("afectividad-aplanamiento-afectivo")==false 
    && sintomas_negativos_afectividad.contains("afectividad-hipotimia"))
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +4 )
    pacienteResponse.actualizarJustificacion("Presenta hipotimia, una particularidad de afectividad muy frecuente en esquizofrenia",1)   
    pacienteResponse.actualizarReglasEjecutadas("Afectividad - Frecuente"); 
end

rule "PUNTAJE: Afectividad - Menos frecuente"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_afectividad.contains("afectividad-aplanamiento-afectivo")==false 
    && sintomas_negativos_afectividad.contains("afectividad-hipotimia")==false 
    && (sintomas_negativos_afectividad.contains("afectividad-timia-displacentera")
    || sintomas_negativos_afectividad.contains("afectividad-hipertimia-displacentera")))
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +2)
    pacienteResponse.actualizarJustificacion("Presenta particularidades en afectividad no tan frecuentes en esquizofrenia (timia displacentera, hipertimia displacentera)",1)   
    pacienteResponse.actualizarReglasEjecutadas("Afectividad - Menos frecuente"); 
end

rule "PUNTAJE: Afectividad - Frecuentes otros diagnosticos"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_afectividad.contains("afectividad-aplanamiento-afectivo")==false 
    && sintomas_negativos_afectividad.contains("afectividad-hipotimia")==false 
    && sintomas_negativos_afectividad.contains("afectividad-timia-displacentera")==false 
    && sintomas_negativos_afectividad.contains("afectividad-hipertimia-displacentera")==false 
    && (sintomas_negativos_afectividad.contains("afectividad-labilidad") 
    || sintomas_negativos_afectividad.contains("afectividad-irritabilidad") 
    || sintomas_negativos_afectividad.contains("afectividad-expansivo")
    || sintomas_negativos_afectividad.contains("afectividad-inapropiado")
    || sintomas_negativos_afectividad.contains("afectividad-anhedonia")))
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +1 )
    pacienteResponse.actualizarJustificacion("Presenta particularidades de afectividad más frecuentes en otros diagnósticos (labilidad, irritabilidad, expansivo, inapropiado, anhedonia)",1)   
    pacienteResponse.actualizarReglasEjecutadas("Afectividad - Frecuentes otros diagnosticos"); 
end

rule "PUNTAJE: Afectividad - Normal"
when
    $pacienteRequest: PacienteRequest(sintomas_negativos_afectividad.contains("afectividad-eutimia"))
then 
    pacienteResponse.setPuntaje(pacienteResponse.getPuntaje() +0 )
    pacienteResponse.actualizarJustificacion("Afectividad normal",1) 
    pacienteResponse.actualizarReglasEjecutadas("Afectividad - Normal");   
end








rule "Evaluar temporal"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_duracion == "Menos de un mes"  
    || sintomas_negativos_duracion== "Menos de un mes")
then
    pacienteResponse.calcularDiagnostico(true);
end

rule "Posible esquizofrenia"
when
    $pacienteRequest: PacienteRequest(sintomas_positivos_duracion == "Mayor o igual a un mes"  
    && sintomas_negativos_duracion== "Mayor o igual a un mes")
then
    pacienteResponse.calcularDiagnostico(false);
end