IF NOT EXISTS (
	SELECT *
	FROM sys.tables t
	WHERE t.name = 'PACIENTES'
)
BEGIN
	CREATE TABLE PACIENTES
	(
		ID_PACIENTE INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		NOMBRE NVARCHAR(100) NOT NULL,
		EDAD INT NOT NULL,
		SEXO NVARCHAR(100) NULL
	)
END

IF NOT EXISTS (
    SELECT *
    FROM sys.tables t
    WHERE t.name = 'MEDICOS'
)
BEGIN
    CREATE TABLE MEDICOS (
        ID_MEDICO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
        DNI INT NOT NULL,
        EMAIL NVARCHAR(100) NOT NULL,
        CONTRASEÑA NVARCHAR(100) NOT NULL,
        NOMBRE NVARCHAR(100) NOT NULL,
        APELLIDO NVARCHAR(100) NOT NULL
    )
	INSERT INTO
		[MEDICOS] (DNI, EMAIL, CONTRASEÑA, NOMBRE, APELLIDO)
	VALUES
		(12345678,'admin@admin.com', 'admin', 'User', 'Admin')
END

IF NOT EXISTS (
    SELECT *
    FROM sys.tables t
    WHERE t.name = 'DIAGNOSTICOS'
)
BEGIN
    CREATE TABLE DIAGNOSTICOS (
        ID_DIAGNOSTICO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
        DIAGNOSTICO NVARCHAR(255) NOT NULL,
        ESTADO BIT NOT NULL,
        COMENTARIOS_MEDICOS NVARCHAR(MAX) NULL,
        COMENTARIOS_RECHAZO NVARCHAR(MAX) NULL,
        JUSTIFICACION NVARCHAR(MAX) NULL,
        RECOMENDACION NVARCHAR(MAX) NULL,
        PUNTAJE INT NULL
    )
END

IF NOT EXISTS (
	SELECT *
	FROM sys.tables t
	WHERE t.name = 'CONSULTAS'
)
BEGIN
	 CREATE TABLE CONSULTAS (
        ID_CONSULTA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
        ID_MEDICO INT NOT NULL FOREIGN KEY REFERENCES MEDICOS(ID_MEDICO),
        ID_PACIENTE INT NOT NULL FOREIGN KEY REFERENCES PACIENTES(ID_PACIENTE),
        FECHA DATE NOT NULL,
        ID_DIAGNOSTICO INT NOT NULL FOREIGN KEY REFERENCES DIAGNOSTICOS(ID_DIAGNOSTICO),
    )
END

IF NOT EXISTS (
	SELECT *
	FROM sys.tables t
	WHERE t.name = 'TIPOS_DIAGNOSTICOS'
)
BEGIN
	CREATE TABLE TIPOS_DIAGNOSTICOS
	(
		ID_TIPO_DIAGNOSTICO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		NOMBRE NVARCHAR(100) NOT NULL
	)
	INSERT INTO TIPOS_DIAGNOSTICOS (NOMBRE)
	VALUES 
		('Esquizofrenia'),
	    ('Evaluar Esquizofrenia Temporal'),
	    ('Esquizofrenia No Posible')
END

IF NOT EXISTS (
    SELECT *
    FROM sys.tables t
    WHERE t.name = 'ESTUDIOS'
)
BEGIN
    CREATE TABLE ESTUDIOS (
        ID_ESTUDIO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
        CAUSA_ORGANICA NVARCHAR(255) NULL, -- SI, NO, INCONCLUSO
        COMENTARIO NVARCHAR(MAX) NULL,
        IMAGEN_PATH NVARCHAR(MAX) NULL
    )
END

IF NOT EXISTS (
    SELECT *
    FROM sys.tables t
    WHERE t.name = 'HISTORIAS_CLINICAS'
)
BEGIN
    CREATE TABLE HISTORIAS_CLINICAS (
        ID_ANTECEDENTE INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
        TRASTORNO_AUTISTA BIT NOT NULL,
        TRASTORNO_COMUNICACION BIT NOT NULL,
        TRASTORNO_ESQUIZOAFECTIVO BIT NOT NULL,
        BIPOLAR_CARAC_PSICOTICAS BIT NOT NULL,
        TRASTORNO_DEPRESIVO BIT NOT NULL,
        ANTECEDENTES_FAMILIARES BIT NOT NULL,
        SUSTANCIAS BIT NOT NULL,
        ID_ESTUDIO INT NOT NULL FOREIGN KEY REFERENCES ESTUDIOS(ID_ESTUDIO),
        ID_PACIENTE INT NOT NULL FOREIGN KEY REFERENCES PACIENTES(ID_PACIENTE)
    )
END

-- SINTOMAS POSITIVOS

IF NOT EXISTS (
    SELECT *
    FROM sys.tables t
    WHERE t.name = 'RITMOS_PENSAMIENTOS'
)
BEGIN
    CREATE TABLE RITMOS_PENSAMIENTOS (
        ID_RITMO_PENSAMIENTO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
        NOMBRE NVARCHAR(100) NOT NULL
    )
	INSERT INTO
		RITMOS_PENSAMIENTOS (NOMBRE)
	VALUES
		('BRADIPSIQUIA'), 
		('TAQUIPSIQUIA'),
		('SIN_PARTICULARIDADES')
END

IF NOT EXISTS (
	SELECT *
	FROM sys.tables t
	WHERE t.name = 'SINTOMAS_POSITIVOS'
)
BEGIN
	CREATE TABLE SINTOMAS_POSITIVOS
	(
		ID_SINTOMA_POSITIVO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
        ID_PACIENTE INT NOT NULL FOREIGN KEY REFERENCES PACIENTES(ID_PACIENTE),
		-- ID_PACIENTE INT NOT NULL,
		-- CONSTRAINT FK_SINTOMAS_POSITIVOS_PACIENTES
		-- FOREIGN KEY (ID_PACIENTE)
		-- REFERENCES PACIENTES(ID_PACIENTE)
        ID_RITMO_PENSAMIENTO INT NOT NULL FOREIGN KEY REFERENCES RITMOS_PENSAMIENTOS(ID_RITMO_PENSAMIENTO),
        DURACION_POSITIVOS NVARCHAR(255) NULL
	)
END

IF NOT EXISTS (
    SELECT *
    FROM sys.tables t
    WHERE t.name = 'ALUCINACIONES'
)
BEGIN
    CREATE TABLE ALUCINACIONES (
        ID_ALUCINACION INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
        NOMBRE NVARCHAR(100) NOT NULL
    )
	INSERT INTO
		ALUCINACIONES (NOMBRE)
	VALUES
		('AUDITIVAS_SIMPLES'),
		('AUDITIVAS_COMPLEJAS'),
		('VISUALES'),
		('OLFATIVAS'),
		('GUSTATIVAS'),
		('CENESTESICAS'),
		('QUINESTESICAS'),
		('EXTRACAMPINAS'),
		('INTRAPSIQUICAS'),
		('NO_SE_DESCARTA'),
		('NO_PRESENTA')
END

IF NOT EXISTS (
    SELECT *
    FROM sys.tables t
    WHERE t.name = 'SINTOMA_ALUCINACIONES'
)
BEGIN
    CREATE TABLE SINTOMA_ALUCINACIONES (
		-- CLAVE COMPUESTA
        ID_ALUCINACION INT NOT NULL FOREIGN KEY REFERENCES ALUCINACIONES(ID_ALUCINACION),
        ID_SINTOMA_POSITIVO INT NOT NULL FOREIGN KEY REFERENCES SINTOMAS_POSITIVOS(ID_SINTOMA_POSITIVO)
    )
END

IF NOT EXISTS (
	SELECT
		*
	FROM
		sys.tables t
	WHERE
		t.name = 'LENGUAJES'
) 

BEGIN 
	CREATE TABLE LENGUAJES (
		ID_LENGUAJE INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		NOMBRE NVARCHAR(100) NOT NULL
	)
	INSERT INTO
		LENGUAJES (NOMBRE)
	VALUES
		('TAQUILALIA'), 
		('VERBORRAGIA'), 
		('BRADILALIA'), 
		('LATENCIA_DE_RESPUESTA'), 
		('MUTISMO'), 
		('MUSITACIONES'), 
		('SOLILOQUIO'), 
		('NEOLOGISMO'), 
		('JERGAFASIA'), 
		('ECOLALIA'), 
		('PARARRESPUESTA'), 
		('ESTEREOTIPIA_VERBAL'), 
		('VERBIGERACION'), 
		('ASOCIACIÓN_POR_HOMOFONÍA'),
		('SIN_PARTICULARIDADES')
END

IF NOT EXISTS (
    SELECT *
    FROM sys.tables t
    WHERE t.name = 'SINTOMA_LENGUAJES'
)
BEGIN
    CREATE TABLE SINTOMA_LENGUAJES (
		-- CLAVE COMPUESTA
        ID_LENGUAJE INT NOT NULL FOREIGN KEY REFERENCES LENGUAJES(ID_LENGUAJE),
        ID_SINTOMA_POSITIVO INT NOT NULL FOREIGN KEY REFERENCES SINTOMAS_POSITIVOS(ID_SINTOMA_POSITIVO)
    )
END

IF NOT EXISTS (
	SELECT
		*
	FROM
		sys.tables t
	WHERE
		t.name = 'PENSAMIENTOS'
) 

BEGIN 
	CREATE TABLE PENSAMIENTOS (
		ID_PENSAMIENTO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		NOMBRE NVARCHAR(100) NOT NULL
	)
	INSERT INTO
		PENSAMIENTOS (NOMBRE)
	VALUES
		('TANGENCIAL'),
		('CIRCUNSTANCIAL'),
		('MINUCIOSIDAD'),
		('VISCOSIDAD'),
		('PENSAMIENTO_CONCRETO'),
		('IDEA_FIJA'),
		('INTERCEPTACION_DEL_PENSAMIENTO'),
		('DISGREGACION'),
		('INCOHERENCIA'),
		('SIN_PARTICULARIDADES')
END 

IF NOT EXISTS (
    SELECT *
    FROM sys.tables t
    WHERE t.name = 'SINTOMA_PENSAMIENTOS'
)
BEGIN
    CREATE TABLE SINTOMA_PENSAMIENTOS (
		-- CLAVE COMPUESTA
        ID_PENSAMIENTO INT NOT NULL FOREIGN KEY REFERENCES PENSAMIENTOS(ID_PENSAMIENTO),
        ID_SINTOMA_POSITIVO INT NOT NULL FOREIGN KEY REFERENCES SINTOMAS_POSITIVOS(ID_SINTOMA_POSITIVO)
    )
END

IF NOT EXISTS (
	SELECT
		*
	FROM
		sys.tables t
	WHERE
		t.name = 'CONTENIDO_PENSAMIENTOS'
) 

BEGIN 
	CREATE TABLE CONTENIDO_PENSAMIENTOS (
		ID_CONTENIDO_PENSAMIENTO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		NOMBRE NVARCHAR(100) NOT NULL
	)
	INSERT INTO
		CONTENIDO_PENSAMIENTOS (NOMBRE)
	VALUES
		('IDEA_FIJA'), 
		('IDEA_OBSESIVA'), 
		('IDEACION_DELIRANTE_SIST'), 
		('IDEACION_DELIRANTE_NO_SIST'), 
		('SIN_PARTICULARIDADES')
END

IF NOT EXISTS (
    SELECT *
    FROM sys.tables t
    WHERE t.name = 'SINTOMA_CONTENIDO_PENSAMIENTOS'
)
BEGIN
    CREATE TABLE SINTOMA_CONTENIDO_PENSAMIENTOS (
		-- CLAVE COMPUESTA
        ID_CONTENIDO_PENSAMIENTO INT NOT NULL FOREIGN KEY REFERENCES CONTENIDO_PENSAMIENTOS(ID_CONTENIDO_PENSAMIENTO),
        ID_SINTOMA_POSITIVO INT NOT NULL FOREIGN KEY REFERENCES SINTOMAS_POSITIVOS(ID_SINTOMA_POSITIVO)
    )
END

-- SINTOMAS NEGATIVOS

IF NOT EXISTS (
	SELECT
		*
	FROM
		sys.tables t
	WHERE
		t.name = 'ATENCIONES'
) 

BEGIN 
	CREATE TABLE ATENCIONES (
		ID_ATENCION INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		NOMBRE NVARCHAR(100) NOT NULL
	)
	INSERT INTO
		ATENCIONES (NOMBRE)
	VALUES
		('EUPROSEXIA'), 
		('HIPOPROSEXIA'), 
		('HIPERPROSEXIA'), 
		('PARAPROSEXIA')
END

IF NOT EXISTS (
	SELECT
		*
	FROM
		sys.tables t
	WHERE
		t.name = 'ACTIVIDADES'
) 

BEGIN 
	CREATE TABLE ACTIVIDADES (
		ID_ACTIVIDAD INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		NOMBRE NVARCHAR(100) NOT NULL
	)
	INSERT INTO
		ACTIVIDADES (NOMBRE)
	VALUES
		('NORMOBULICO'), 
		('ABULIA'), 
		('HIPOBULIA'), 
		('HIPERBULIA_PRODUCTIVA'), 
		('HIPERBULIA_IMPRODUCTIVA'), 
		('COMPULSIONES'), 
		('APRAXIA'), 
		('ATAXIA'), 
		('ECOPRAXIA'), 
		('MANIERISMO'), 
		('ESTEREOTIPIA_MOTORA'), 
		('INTERCEPTACION_CINETICA'), 
		('NEGATIVISMO'), 
		('OBEDIENCIA_AUTOMATICA'), 
		('FLEXIBILIDAD_CEREA')
END

IF NOT EXISTS (
	SELECT *
	FROM sys.tables t
	WHERE t.name = 'SINTOMAS_NEGATIVOS'
)
BEGIN
	CREATE TABLE SINTOMAS_NEGATIVOS
	(
		ID_SINTOMA_NEGATIVO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
        ID_PACIENTE INT NOT NULL FOREIGN KEY REFERENCES PACIENTES(ID_PACIENTE),
		-- ID_PACIENTE INT NOT NULL,
		-- CONSTRAINT FK_SINTOMAS_NEGATIVOS_PACIENTES
		-- FOREIGN KEY (ID_PACIENTE)
		-- REFERENCES PACIENTES(ID_PACIENTE)
        ID_ATENCION INT NOT NULL FOREIGN KEY REFERENCES ATENCIONES(ID_ATENCION),
        ID_ACTIVIDAD INT NOT NULL FOREIGN KEY REFERENCES ACTIVIDADES(ID_ACTIVIDAD),
        DURACION_NEGATIVOS NVARCHAR(255) NULL
	)
END

IF NOT EXISTS (
	SELECT
		*
	FROM
		sys.tables t
	WHERE
		t.name = 'ASPECTOS'
) 

BEGIN 
	CREATE TABLE ASPECTOS (
		ID_ASPECTO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		NOMBRE NVARCHAR(100) NOT NULL
	)
	INSERT INTO
		ASPECTOS (NOMBRE)
	VALUES
		('FACIE'), 
		('ALIÑO'), 
		('ASEO'), 
		('BIZARRO'), 
		('EXTRAVAGANTE'), 
		('INADECUADO'), 
		('ADELGAZADO'), 
		('HIPOMÍMICO')
END

IF NOT EXISTS (
    SELECT *
    FROM sys.tables t
    WHERE t.name = 'SINTOMA_ASPECTOS'
)
BEGIN
    CREATE TABLE SINTOMA_ASPECTOS (
		-- CLAVE COMPUESTA
        ID_ASPECTO INT NOT NULL FOREIGN KEY REFERENCES ASPECTOS(ID_ASPECTO),
        ID_SINTOMA_NEGATIVO INT NOT NULL FOREIGN KEY REFERENCES SINTOMAS_NEGATIVOS(ID_SINTOMA_NEGATIVO)
    )
END

IF NOT EXISTS (
	SELECT
		*
	FROM
		sys.tables t
	WHERE
		t.name = 'AFECTIVIDADES'
) 

BEGIN 
	CREATE TABLE AFECTIVIDADES (
		ID_AFECTIVIDAD INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		NOMBRE NVARCHAR(100) NOT NULL
	)
	INSERT INTO
		AFECTIVIDADES (NOMBRE)
	VALUES
		('EUTIMIA'), 
		('TIMIA_DISPLACENTERA'), 
		('HIPERTIMIA_PLACENTERA'), 
		('HIPERTIMIA_DISPLACENTERA'), 
		('HIPOTIMIA'), 
		('APLANAMIENTO_AFECTIVO'), 
		('LABILIDAD'), 
		('IRRITABILIDAD'), 
		('EXPANSIVO'), 
		('INAPROPIADO'), 
		('ANHEDONIA')
END


IF NOT EXISTS (
    SELECT *
    FROM sys.tables t
    WHERE t.name = 'SINTOMA_AFECTIVIDADES'
)
BEGIN
    CREATE TABLE SINTOMA_AFECTIVIDADES (
		-- CLAVE COMPUESTA
        ID_AFECTIVIDAD INT NOT NULL FOREIGN KEY REFERENCES AFECTIVIDADES(ID_AFECTIVIDAD),
        ID_SINTOMA_NEGATIVO INT NOT NULL FOREIGN KEY REFERENCES SINTOMAS_NEGATIVOS(ID_SINTOMA_NEGATIVO)
    )
END

-- IF NOT EXISTS (
-- 	SELECT
-- 		*
-- 	FROM
-- 		sys.tables t
-- 	WHERE
-- 		t.name = 'DURACION_SINTOMAS_NEGATIVOS'
-- ) 

-- BEGIN 
-- 	CREATE TABLE DURACION_SINTOMAS_NEGATIVOS (
-- 		ID_DURACION_SINTOMA_NEGATIVO INT NOT NULL IDENTITY (1, 1) PRIMARY KEY,
-- 		NOMBRE VARCHAR(255) NOT NULL
-- 	)
-- 	INSERT INTO
-- 		DURACION_SINTOMAS_NEGATIVOS (NOMBRE)
-- 	VALUES
-- 		('MENOR_1_MES'), 
-- 		('MAYOR_IGUAL_1_MES') 
-- END




-- COMPLEMENTARIOS



-- ANTECEDENTES

-- IF NOT EXISTS (
-- 	SELECT
-- 		*
-- 	FROM
-- 		sys.tables t
-- 	WHERE
-- 		t.name = 'ANTECEDENTES'
-- ) 

-- BEGIN 
-- 	CREATE TABLE ANTECEDENTES (
-- 		ID_ANTECEDENTE INT NOT NULL IDENTITY (1, 1) PRIMARY KEY,
-- 		ANTECEDENTE_AUTISTA BOOLEAN NOT NULL,
-- 		ANTECEDENTE_TRASTORNO_COMUNICACION BOOLEAN NOT NULL,
-- 		TRASTORNO_ESQUIZOAFECTIVO BOOLEAN NOT NULL,
-- 		BIPOLAR_CARAC_PSICOTICAS BOOLEAN NOT NULL,
-- 		TRASTORNO_DEPRESIVO BOOLEAN NOT NULL,
-- 		ANTECEDENTES_FAMILIARES BOOLEAN NOT NULL
-- 	)
-- END




-- DIAGNOSTICO Y RESULTADOS

-- IF NOT EXISTS (
-- 	SELECT *
-- 	FROM sys.tables t
-- 	WHERE t.name = 'DIAGNOSTICOS'
-- )
-- BEGIN
-- 	CREATE TABLE DIAGNOSTICOS
-- 	(
-- 		ID_DIAGNOSTICOS INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
-- 		NOMBRE NVARCHAR(100) NOT NULL
-- 	)
-- 	INSERT INTO DIAGNOSTICOS (NOMBRE)
-- 	VALUES 
-- 		('Esquizofrenia'),
-- 	    ('Evaluar Esquizofrenia Temporal'),
-- 	    ('Esquizofrenia No Posible')
-- END

-- IF NOT EXISTS (
-- 	SELECT *
-- 	FROM sys.tables t
-- 	WHERE t.name = 'ESTADOS'
-- )
-- BEGIN
-- 	CREATE TABLE ESTADOS
-- 	(
-- 		ID_ESTADO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
-- 		NOMBRE NVARCHAR(100) NOT NULL
-- 	)
-- 	INSERT INTO SE_ESTADOS (NOMBRE)
-- 	VALUES ('Confirmado'),
-- 	       ('Rechazado')
-- END


-- IF NOT EXISTS (
-- 	SELECT *
-- 	FROM sys.tables t
-- 	WHERE t.name = 'PACIENTES'
-- )
-- BEGIN
-- 	CREATE TABLE PACIENTES
-- 	(
-- 		ID_PACIENTE INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
-- 		NOMBRE NVARCHAR(100) NOT NULL,
-- 		EDAD INT NOT NULL,
-- 		SEXO NVARCHAR(100) NULL
-- 	)
-- END


-- IF NOT EXISTS (
-- 	SELECT *
-- 	FROM sys.tables t
-- 	WHERE t.name = 'DIAGNOSTICOS'
-- )
-- BEGIN
-- 	CREATE TABLE DIAGNOSTICOS
-- 	(
-- 		ID_DIAGNOSTICO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
-- 		ID_CONSULTA INT NOT NULL,  -- Agregar FK
-- 		DIAGNOSTICO NVARCHAR(100) NOT NULL,
-- 		ESTADO INT NOT NULL,  -- Agregar FK
-- 		-- FECHA NVARCHAR(100) NOT NULL,
-- 		JUSTIFICACION NVARCHAR(4000) NULL,
-- 		RECOMENDACION NVARCHAR(1000) NOT NULL,
-- 		COMENTARIOS_MEDICOS NVARCHAR(4000) NULL,
-- 		COMENTARIOS_RECHAZO NVARCHAR(4000) NULL,
-- 		PUNTAJE INT NOT NULL
-- 	)
-- END

--IF NOT EXISTS (
--	SELECT *
--	FROM sys.tables t
--	WHERE t.name = 'PACIENTES'
--)
--BEGIN
--	CREATE TABLE PACIENTES
--	(
--		ID_SE_PACIENTE_RESULTADO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
--		COD_PACIENTE NVARCHAR(50) NOT NULL,
--		SEXO NVARCHAR(100) NOT NULL,
--		EDAD INT NOT NULL,
--		INMUNODEPRESION NVARCHAR(2) NOT NULL,
--		PROTECCION_SOLAR NVARCHAR(2) NOT NULL,
--		ANTECEDENTES_PROPIOS NVARCHAR(2) NOT NULL,
--		ANTECEDENTES_FAMILIARES NVARCHAR(2) NOT NULL,
--		DIAMETRO NVARCHAR(50) NOT NULL,
--		ASIMETRICO NVARCHAR(2) NOT NULL,
--		BORDES_IRREGULARES NVARCHAR(2) NOT NULL,
--		CAMBIO_TAMANIO NVARCHAR(2) NOT NULL,
--		CAMBIO_COLOR NVARCHAR(2) NOT NULL,
--		POSIBLES_CAUSAS NVARCHAR(1000) NOT NULL,
--		RECOMENDACION NVARCHAR(500) NOT NULL,
--		COMENTARIOS_MEDICOS NVARCHAR(4000) NULL,
--		COMENTARIOS_RECHAZO NVARCHAR(4000) NULL,
--		ID_TIPO_ANTECEDENTES_PROPIOS INT NULL,
--		ID_SE_FOTOTIPO_PIEL INT NOT NULL,
--		ID_TIPO_ANTECEDENTES_FAMILIARES INT NULL,
--		ID_SE_COLOR INT NOT NULL,
--		ID_SE_UBICACION INT NOT NULL,
--		ID_SE_RIESGO INT NOT NULL,
--		ID_SE_IMAGEN INT NULL,
--		ID_SE_ESTADO INT NOT NULL
--	)
--END